version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - DEVELOPMENT_BASE_URL=
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    
  backend:
    container_name: backend
    build: ./backend
    command: yarn start:dev
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mongodb+srv://tvapp:szszukeme54321@cluster0.rwoun.mongodb.net/realestate?retryWrites=true&w=majority&ssl=true
    volumes:
      - ./backend:/backend
      - /backend/node_modules
   

 
   
  


   
